Trim to simplify the script, for now

diff --git a/scala-runner b/scala-runner
--- a/scala-runner
+++ b/scala-runner
@@ -5,47 +5,35 @@
 # https://github.com/dwijnand/scala-runners
 
 app_name=$(basename "$0")
+
 declare -r app_name
-
-declare scala_version=latest.stable
-
-declare verbose
+declare -g scala_version=latest.stable
 declare -a residual_args
 
-echoerr() { echo >&2 "$@"; }
-vlog()    { [[ -n "$verbose" ]] && echoerr "$@"; }
-die()     { echo "Aborting: $*" ; exit 1; }
+require_arg() {
+  local type="$1"
+  local opt="$2"
+  local arg="$3"
 
-setScalaVersion() { scala_version="$1"; }
-
-addResidual() { vlog "[residual] arg = '$1'"  ; residual_args+=("$1"); }
-
-process_args() {
-  require_arg() {
-    local type="$1"
-    local opt="$2"
-    local arg="$3"
-
-    if [[ -z "$arg" ]] || [[ "${arg:0:1}" == "-" ]]; then
-      die "$opt requires <$type> argument"
-    fi
-  }
-  while [[ $# -gt 0 ]]; do
-    case "$1" in
-      --scala-version) require_arg version "$1" "$2" && setScalaVersion "$2" && shift 2 ;;
-                  -28) setScalaVersion "2.8+"  && shift ;;
-                  -29) setScalaVersion "2.9+"  && shift ;;
-                 -210) setScalaVersion "2.10+" && shift ;;
-                 -211) setScalaVersion "2.11+" && shift ;;
-                 -212) setScalaVersion "2.12+" && shift ;;
-                 -213) setScalaVersion "2.13+" && shift ;;
-               # -214) setScalaVersion "2.14+" && shift ;;  # soon(tm)
-               #   -3) setScalaVersion "3+"    && shift ;;  # soon(tm)
-                    *) addResidual "$1"        && shift ;;
-    esac
-  done
+  if [[ -z "$arg" ]] || [[ "${arg:0:1}" == "-" ]]; then
+    echo "Aborting: $opt requires <$type> argument"
+    exit 1
+  fi
 }
 
-process_args "$@"
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    --scala-version) require_arg version "$1" "$2" && scala_version="$2" && shift 2 ;;
+                -28) scala_version="2.8+"  && shift ;;
+                -29) scala_version="2.9+"  && shift ;;
+               -210) scala_version="2.10+" && shift ;;
+               -211) scala_version="2.11+" && shift ;;
+               -212) scala_version="2.12+" && shift ;;
+               -213) scala_version="2.13+" && shift ;;
+             # -214) scala_version="2.14+" && shift ;;  # soon(tm)
+             #   -3) scala_version="3+"    && shift ;;  # soon(tm)
+                  *) residual_args+=("$1")   && shift ;;
+  esac
+done
 
 coursier launch "$app_name:$scala_version" -- "${residual_args[@]}"
