Handle getScalaBaseVersion failing
Before:

  $ scala -v --scala-pr 1234567
  [setScalaPrVersion] arg = '1234567'
  [getScalaBaseVersion] arg = 'pull/1234567/head'
  [setScalaVersion] arg = '-bin-null-SNAPSHOT'
  [addCoursier] arg = '-r'
  [addCoursier] arg = 'https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots'
  # Executing command line:
  cs
  launch
  scala:-bin-null-SNAPSHOT
  -r
  https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots
  --

  Resolution error: Error downloading org.scala-lang:scala-compiler:-bin-null-SNAPSHOT
    not found: /Users/dnw/.ivy2/local/org.scala-lang/scala-compiler/-bin-null-SNAPSHOT/ivys/ivy.xml
    not found: https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/-bin-null-SNAPSHOT/scala-compiler--bin-null-SNAPSHOT.pom
    not found: https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/org/scala-lang/scala-compiler/-bin-null-SNAPSHOT/scala-compiler--bin-null-SNAPSHOT.pom

After:

  $ ./scala -v --scala-pr 1234567
  [setScalaPrVersion] arg = '1234567'
  [getScalaBaseVersion] arg = 'pull/1234567/head'
  Aborting: Failed to get scala base version for PR 1234567

Fixes #24

diff --git a/scala-runner b/scala-runner
--- a/scala-runner
+++ b/scala-runner
@@ -18,6 +18,7 @@ declare -r scala_pr_builds_url=https://scala-ci.typesafe.com/artifactory/scala-p
 
 echoerr() { echo >&2 "$@"; }
 vlog()    { [[ -n "$verbose" ]] && echoerr "$@"; }
+die()     { echo "Aborting: $*"; exit 1; }
 dropR()   { echo "${1:0:$((${#1} - $2))}"; } # https://superuser.com/q/1033273 ${1:0:-5} (bash 4.2+)
 
 checkHub() {
@@ -38,13 +39,18 @@ addCoursier () {
 }
 getScalaBaseVersion() {
   vlog "[getScalaBaseVersion] arg = '$1'"
-  local base_version=$(hub api -H "Accept: application/vnd.github.v3.raw" "repos/scala/scala/contents/build.sbt?ref=$1" | grep -E '(baseVersion in Global|Global / baseVersion\b)' | sed 's/.*"\(.*\)".*/\1/')
+  local build_sbt
+  build_sbt=$(hub api -H "Accept: application/vnd.github.v3.raw" "repos/scala/scala/contents/build.sbt?ref=$1")
+  [ $? -ne 0 ] && exit 1
+  local base_version=$(grep -E '(baseVersion in Global|Global / baseVersion\b)' <<< "$build_sbt" | sed 's/.*"\(.*\)".*/\1/')
   local cross=$(grep -q -E '\d+\.\d+.0' <<< "$base_version" && echo "-pre" || echo "-bin")
   echo "$base_version$cross"
 }
 getScalaHead() {
   vlog "[getScalaHead] arg = '$1'"
-  local base_version=$(getScalaBaseVersion "heads/$1")
+  local base_version
+  base_version=$(getScalaBaseVersion "heads/$1")
+  [ $? -ne 0 ] && exit 1
   local refInfo=$(hub api "repos/scala/scala/git/ref/heads/$1")
   local sha=$(jq -r '.object.sha' <<< "$refInfo")
   echo "$base_version-${sha:0:7}"
@@ -69,8 +75,10 @@ setScalaVersion() {
 }
 setScalaPrVersion() {
   vlog "[setScalaPrVersion] arg = '$1'"
+  local base_version
   checkHub
-  local base_version=$(getScalaBaseVersion "pull/$1/head")
+  base_version=$(getScalaBaseVersion "pull/$1/head")
+  [ $? -ne 0 ] && die "Failed to get scala base version for PR $1"
   local prInfo=$(hub api "repos/scala/scala/pulls/$1")
   local sha=$(jq -r '.head.sha' <<< "$prInfo")
   setScalaVersion "$base_version-${sha:0:7}-SNAPSHOT"
